version: "3.8"
services:
  random_num:
    build: .
    container_name: rand_con
    command: python random_num.py
  guess:
    build: .
    container_name: guess_con
    command: python guess.py
    stdin_open: true
    tty: true
